### PR TITLE
upgrade to latest nx version

### PR DESCRIPTION
**Pull request by kattsushi**

### CODE REVIEW

**Comment by guiseek** [comment]
Thank you so much for your contribution @kattsushi, your collaboration is greatly appreciated and makes a difference for this project to be maintained!

With the update we will need to change the package into which we import the `libraryGenerator` `function`, which has been moved from the `@nrwl/workspace` package to `@nx/js`, if you can, and change the `runTasksInSerial` `function` from package `@nx/workspace/src/utilities/run-tasks-in-serial` to `@nx/devkit`, that would be nice too.

Could you please make this change on all generators please?

**Comment by kattsushi** [comment]
yes, right now I'm dealing with the peer dependencies and migration to make the demos app work as before, but yes after that I gonna continue with that because I have a couple of ideas for additional generators like value objects and abstract entities and common/core utilities

**Comment by guiseek** [comment]
> yes, right now I'm dealing with the peer dependencies and migration to make the demos app work as before, but yes after that I gonna continue with that because I have a couple of ideas for additional generators like value objects and abstract entities and common/core utilities

Great @kattsushi, I'm excited about this message!

**Comment by kattsushi** [comment]
@guiseek  any thoughts about this issue 
image
tried to look forward in the documentation but i didn found any deprecation guide

**Comment by guiseek** [comment]
> tried to look forward in the documentation but i didn found any deprecation guide

Sorry for the delay, I was teaching at the university.

Yes! this has been deprecated.. this was being used to set up the repository's default project...

if you look further down, you'll see that the functions `updateWorkspaceConfiguration` and `readWorkspaceConfiguration` are also marked as deprecated... the equivalent functions now are `updateNxJson` and `readNxJson` and now comes `setDefaultCollection`.

this function is no longer necessary, since it is possible to do the same thing with the `JSON` returned from the `readNxJson` function.

So realizing the ideas, it would look something like this here:

```ts

import {
  // ...
  updateNxJson,
  readNxJson,
} from '@nx/devkit';

function setDefaults(host: Tree, options: InitGeneratorSchema) {
  const workspace = readNxJson(host);

  workspace.generators = workspace.generators || {};
  workspace.generators['@nx-clean/plugin-core'] = {
    data: { injectable: options.injectable },
    domain: { injectable: options.injectable },
    presentation: { injectable: options.injectable },
    repository: { injectable: options.injectable },
    ...(workspace.generators['@nx-clean/plugin-core'] || {}),
  };
  //             👇
  workspace.defaultProject = '@nx-clean/plugin-core'

  updateNxJson(host, workspace);
}
```

**Comment by guiseek** [comment]
@kattsushi actually I'm wanting to think about it again, but I believe now is not a good time, let's finish this PR and then we'll think about changes

**Comment by guiseek** [comment]
come on @kattsushi 

the error now happened because the `npm ci` command is used to install the packages, and it is mandatory that there is a `package.json` file, because this command installs exactly the same versions that were installed when npm install was executed and `package-lock.json` was generated.

I believe we will have a lot of trouble adjusting all versions at this point, mainly due to dependencies on the `react` and `@material*` library. to resolve it as something momentary, you can change the `npm ci` command from the `.github/**/*.yml` files to `npm install --legacy-peer-deps`.

With the merge done, I'll stop to calmly analyze and refactor the examples, organizing and reducing the number of dependencies...

What do you think?

**Comment by kattsushi** [comment]
@guiseek no worries!, right now the demos are working also the test are passing only left test the generators locally probably that issue about set default function cause some issues if I found some workaround I will open another PR

**Comment by guiseek** [comment]
@kattsushi I sent you an invitation to collaborate with the project, you can see it on github or in your email box

**Comment by kattsushi** [comment]
@guiseek how can we run the plugin locally ? im trying couples of ways but without success probably i am missing something

`nx generate @nx-clean/plugin-core:domain --name=domain --entity=user --directory=account  --repository --usecases --tags=type:domain,scope:account`

image
Interesting... seems like there is a naming collision between @nx-clean/core and @nx-clean/plugin-core, recognize the first one as a plugin but is not

**Comment by guiseek** [comment]
> @guiseek how can we run the plugin locally ? im trying couples of ways but without success probably i am missing something
> 
> `nx generate @nx-clean/plugin-core:domain --name=domain --entity=user --directory=account --repository --usecases --tags=type:domain,scope:account`
> 
> image Interesting... seems like there is a naming collision between @nx-clean/core and @nx-clean/plugin-core, recognize the first one as a plugin but is not

@kattsushi sorry man! the last few days have been crazy

ok, for you to try locally, you need to use the npm link command...

steps:
1. then build the nx-clean generators and then
2. go to the `dist/libs/plugin/core directory` *(I think that's it, but check it out)* and run: `npm link`
3. create a new monorepo outside of nx-clean and try to install nx clean in it by running: `npm link @nx-clean/plugin-core`

see if it works, if it doesn't work let me know and then we configure Verdaccio in the repository

**Comment by kattsushi** [comment]
> > @guiseek how can we run the plugin locally ? im trying couples of ways but without success probably i am missing something
> > `nx generate @nx-clean/plugin-core:domain --name=domain --entity=user --directory=account --repository --usecases --tags=type:domain,scope:account`
> > image Interesting... seems like there is a naming collision between @nx-clean/core and @nx-clean/plugin-core, recognize the first one as a plugin but is not
> 
> @kattsushi sorry man! the last few days have been crazy
> 
> ok, for you to try locally, you need to use the npm link command...
> 
> steps:
> 
> 1. then build the nx-clean generators and then
> 2. go to the `dist/libs/plugin/core directory` _(I think that's it, but check it out)_ and run: `npm link`
> 3. create a new monorepo outside of nx-clean and try to install nx clean in it by running: `npm link @nx-clean/plugin-core`
> 
> see if it works, if it doesn't work let me know and then we configure Verdaccio in the repository

yes working! thank you, now i was able to, with that i'm sure to do not break anything related to the currently generators, can i go a head to merge this PR to start working first on reduce the dependencies and fix the CI part to work as before and continue with some item and ideas that i put in the discussion section

**Pull request merged**
